/* Generated by the Nim Compiler v2.0.4 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;

function returnTest() {
  var result_536870914 = null;

  BeforeRet: {
    result_536870914 = "Hello, World!";
    break BeforeRet;
  };

  return result_536870914;

}
